DROP TABLE VETERINARIOS IF EXISTS;

CREATE TABLE VETERINARIOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
nroLicencia VARCHAR(50) NOT NULL,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
especialidad VARCHAR(50) NOT NULL
);